---
- hosts: all
  become: true
  tasks:
   - name: copy ini
     copy:
       src:  /var/lib/jenkins/workspace/TestJob/app.ini
       dest: /home/web/www/app.ini
   - name: copy service
     copy:
       src: /var/lib/jenkins/workspace/TestJob/app/app.service
       dest: /etc/systemd/system/app.service
     notify: restart flask app
     
   - name: copy site conf
     copy:
        src: /var/lib/jenkins/workspace/TestJob/app/app.conf
        dest: /etc/nginx/sites-enabled/app.conf
     notify: restart nginx
     
   - name: copy app file
     copy:
        src: /var/lib/jenkins/workspace/TestJob/app.py
        dest: /home/web/www/app.py
   - name: copy uwsgi file
     copy:
        src: /var/lib/jenkins/workspace/TestJob/wsgi.py
        dest: /home/web/www/wsgi.py
        
   - name: remove default site
     file: path=/etc/nginx/sites-enabled/default state=absent
     
   - name: just force systemd to reread configs
     systemd: daemon_reload=yes
  handlers:
    
    - name: restart flask app
      service: name=app state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
