---
- hosts: all
  become: true
  tasks:
   - name: copy ini
     copy:
       src:  /var/lib/jenkins/workspace/TestJob/app.ini
       dest: /home/web/www/app.ini
   - name: copy service
     copy:
       src: /var/lib/jenkins/workspace/TestJob/app/app.service
       dest: /etc/systemd/system/app.service
   - name: copy site conf
     copy:
        src: /var/lib/jenkins/workspace/TestJob/app/app.conf
        dest: /etc/nginx/sites-enabled/app.conf
     notify: restart nginx
   - name: copy app file
     copy:
        src: /var/lib/jenkins/workspace/TestJob/{{item}}
        dest: /home/web/www/
     with_fileglob: "*.py"

  handlers:
    - name: restart flask app
      service: name=app state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
