- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: flaskapp
    default_container_image: annvzel/jenkinsdocker
  tasks:
    - debug: msg="{{ lookup('env','D_USERNAME') }}"
    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('env',D_USERNAME) }}"
        password: "{{ lookup('env',D_PASSWORD) }}"
        
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present