- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: flaskapp
    default_container_image: annvzel/jenkinsdocker
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('env','USER') }}"
        password: "{{ lookup ('env','PASSWORD')}}"
        
    - debug:
        msg: User {{username}}
        
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: present