- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: flaskapp
    default_container_image: "{{D_REG}}"
  tasks:
    - debug: msg="{{ D_USER }}"
    - name: Log into DockerHub
      docker_login:
        username: "{{ D_USER }}"
        password: "{{ D_PASS }}"
        
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Delete container if exists 
      docker_container:
       name: "{{ default_container_name }}"
       state: absent
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        ports:
           - "80:8000"
        state: started